### ISSUE TITLE
Support Asyncer r2dbc-mysql

### ISSUE THREAD

**Issue by DmitryKubahov** [micronaut-projects/micronaut-r2dbc#357]
### Feature description

Last release `dev.miku:r2dbc-mysql` was on **12.07.2020** which is almost 3 years ago. It does not support `r2dbc-spi` version > `0.8.6`.
I would suggest using `io:asycner:r2dbc-mysql` instead of `dev.miku:r2dbc-mysql` since the latter is out of date and inactive for a long time.
The `io:asyncer:2dbc-mysql` is the official successor to `dev.miku:r2dbc-mysql`.
GitHub: https://github.com/asyncer-io/r2dbc-mysql
#https://github.com/mirromutth/r2dbc-mysql/pull/249#issuecomment-1493394792

**Comment by radovanradic** [comment]
This did not work well as expected, does not handle dates compatibly with previous version. Reverting changes for now.

**Comment by radovanradic** [comment]
Added support for this driver in 5.0.0-M7 release. Still seeing issues in micronaut-data tests using this library so we keep both drivers.

**Comment by jchrys** [comment]
Hello,  @radovanradic and Microanut team.
We've just resolved the issue related on this thread and checked on my environment
I would greatly appreciate it if you could spare a moment to check the updated version(`1.0.3-SNAPSHOT`) and confirm the issue is resolved. (our snapshot repository is `https://s01.oss.sonatype.org/content/repositories/snapshots`) Your validation would be invaluable.

**Comment by radovanradic** [comment]
> Hello, @radovanradic and Microanut team. We've just resolved the issue related on this thread and checked on my environment I would greatly appreciate it if you could spare a moment to check the updated version(`1.0.3-SNAPSHOT`) and confirm the issue is resolved. (our snapshot repository is `https://s01.oss.sonatype.org/content/repositories/snapshots`) Your validation would be invaluable.

Hello @jchrys ,

I tested 1.0.3-SNAPSHOT and can confirm issue with dates is gone. But, there was another issue and is still present when running mysql tests. After some number of tests are executed, we start getting this error

> Lock wait timeout exceeded; try restarting transaction
io.r2dbc.spi.R2dbcTimeoutException: [1205] [HY000] Lock wait timeout exceeded; try restarting transaction

which we are not seeing with dev-miku library. If you want to test, I have created branch using 1.0.3-SNAPSHOT here https://github.com/micronaut-projects/micronaut-data and branch is `r2dbc-mysql-asyncer-testing` so you can check it out and test `data-r2dbc/src/test/groovy/mysql` package in IntelliJ. Running now in github, we'll see if it fails there too.

**Comment by jchrys** [comment]
Thank you for testing and creating the branch. 
We'll investigate the "Lock wait timeout exceeded" issue and get back to you soon. 
Your help is greatly appreciated. Thanks again! 👍

**Comment by jchrys** [comment]
My apologies for the delay in getting back to you. (I was away on vacation)
I have identified the underlying issue (the connection might be closed prematurely when there are ongoing requests).
I will fix this issue soon. Thank you for your understanding! 😊

**Comment by jchrys** [comment]
Hello, @radovanradic.
I have fixed it. Could you please confirm? (1.0.3-SNASPHOT)

**Comment by radovanradic** [comment]
@jchrys Yes, I have tested our code with your latest changes and the tests are passing now. Once 1.0.3 is published we will use it. Thanks

**Comment by jchrys** [comment]
@radovanradic  Thank you very much for confirming. :D We've just released it after internal testing.
